### ISSUE TITLE
Distance measurements

### ISSUE THREAD

**Issue by ghost** [Developer-Student-Clubs-UBa/Flow#11]
Distance measurements not provided..... This is due to the fact that individuals location is unknown for calculating the approximate distance to the various taps![Screenshot_20210328-235401.png](https://user-images.githubusercontent.com/81165345/112770925-1674b580-9021-11eb-8536-4681641d6b16.png)

**Comment by bernandez** [comment]
Please turn on your location

**Comment by Burnleydel** [comment]
Aight
